[env]
TESTING_CONTENT_ROOT = { value = "tests/data/content/files", relative = true }
TESTING_CONTENT_TRANSLATED_ROOT = { value = "tests/data/translated_content/files", relative = true }
TESTING_CACHE_CONTENT = "0"
TESTING_READER_IGNORES_GITIGNORE = "1"
TS_RS_EXPORT_DIR = "../../typescript_bindings"
