name: PR Review Companion

on:
  workflow_call:
    inputs:
      rari-binary-artifact-id:
        description: "ID of rari binary artifact (optional)"
        type: string
        default: ""

permissions:
  contents: read
  # Authenticate with GCP (same as _deploy.yml).
  id-token: write
  # Post comment in pull request.
  pull-requests: write

jobs:
  build-binary:
    if: |
      inputs.rari-binary-artifact-id == '' &&
      github.repository_owner == 'mdn' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.secret_source == 'Actions'
    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Build rari
        run: cargo build --release

      - name: Upload binary
        id: upload
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: rari-binary-pr${{ github.event.pull_request.number }}
          path: target/release/rari
          retention-days: 1

  build:
    if: |
      always() &&
      (needs.build-binary.result == 'success' || needs.build-binary.result == 'skipped') &&
      github.repository_owner == 'mdn' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.secret_source == 'Actions'
    needs: build-binary
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      partial: true
      rari-binary-artifact-id: ${{ inputs.rari-binary-artifact-id || needs.build-binary.outputs.artifact-id }}

  deploy:
    if: always() && needs.build.result == 'success'
    needs: build
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      cancel-in-progress: true
      prefix: rari-pr${{ github.event.pull_request.number }}
      build-artifact-name: ${{ needs.build.outputs.artifact-name }}

  comment:
    if: always() && needs.deploy.result == 'success'
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Comment in PR
        run: |
          COMMENT_ID=$(gh pr view "$PR_NUMBER" --repo "${{ github.repository }}" --comments --json comments \
            --jq ".comments | sort_by(.createdAt) | map(select(.author.login == \"github-actions\")) | .[0].id")
          if [ -n "$COMMENT_ID" ]; then
            gh api graphql -f query='
                mutation($id:ID!, $body:String!) {
                  updateIssueComment(input:{id:$id, body:$body}) {
                    issueComment {
                      id
                    }
                  }
                }' -f id="$COMMENT_ID" -f body="$BODY"
          else
            gh pr comment "$PR_NUMBER" --repo "${{ github.repository }}" --body "$BODY"
          fi
        env:
          BODY: "${{ github.sha }} was deployed to: ${{ needs.deploy.outputs.url }}"
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ github.token }}
