name: publish-npm

on:
  workflow_run:
    workflows: [build-and-upload-binaries]
    types: [completed]

permissions:
  id-token: write # OIDC for npm Trusted Publishing

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Checkout
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: "./rari-npm/package.json"
          package-manager-cache: false

      # Ensure npm 11.5.1 or later for trusted publishing
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Generate Schema
        working-directory: ./rari-npm
        run: npm install && npm run export-schema && npm run generate-types
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        working-directory: ./rari-npm
        run: npm publish --access public --provenance
