name: publish-npm-manual

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "actually publish"
        required: true
        default: false
        type: boolean

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Checkout
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: "./rari-npm/package.json"
          package-manager-cache: false

      - name: Test Publish
        if: ${{ ! inputs.publish }}
        working-directory: ./rari-npm
        run: npm publish --access public --dry-run

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: ./rari-npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
