name: publish-npm

on:
  workflow_run:
    workflows: [build-and-upload-binaries]
    types: [completed]

permissions:
  id-token: write # OIDC for npm Trusted Publishing

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Checkout
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: "./rari-npm/package.json"
          package-manager-cache: false

      # Ensure npm 11.5.1 or later for trusted publishing
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Generate Schema
        working-directory: ./rari-npm
        run: npm install && npm run export-schema && npm run generate-types
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        working-directory: ./rari-npm
        run: npm publish --access public --provenance
