name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

permissions: {} # No GITHUB_TOKEN permissions, as we only use it to increase API limit.

env:
  CONTENT_ROOT: ${{ github.workspace }}/content/files
  CONTENT_TRANSLATED_ROOT: ${{ github.workspace }}/translated-content/files
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90

      - name: sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Build
        run: cargo build --release --verbose

      - name: Upload rari binary
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: rari-binary
          path: target/release/rari
          retention-days: 1

  format:
    needs: build
    runs-on: ubuntu-latest

    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90
        with:
          components: rustfmt

      - name: sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Run fmt
        run: cargo fmt -- --check

  test:
    needs: build
    runs-on: ubuntu-latest

    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90

      - name: sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Run tests
        run: cargo test --verbose --workspace --all-targets --no-fail-fast

      - name: Run doc tests
        run: cargo test --verbose --workspace --doc --features doctest --no-fail-fast

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-features --workspace -- -Dwarnings

  fix-flaws:
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/_run.yml
    with:
      command: content fix-flaws
      translated-content: true
      diff: true

  fmt-sidebars:
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/_run.yml
    with:
      command: content fmt-sidebars
      diff: true

  sync-sidebars:
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/_run.yml
    with:
      command: content sync-sidebars
      diff: true

  sync-translated-content:
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/_run.yml
    with:
      command: content sync-translated-content
      translated-content: true
      diff: true

  validate-redirects:
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/_run.yml
    with:
      command: content validate-redirects
      translated-content: true
