name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

permissions: {} # No GITHUB_TOKEN permissions, as we only use it to increase API limit.

env:
  CONTENT_ROOT: ${{ github.workspace }}/content/files
  CONTENT_TRANSLATED_ROOT: ${{ github.workspace }}/translated-content/files
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90

      - name: sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Build
        run: cargo build --release --verbose

      - name: Upload rari binary
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: rari-binary
          path: target/release/rari
          retention-days: 1

  format:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90
        with:
          components: rustfmt

      - name: Run fmt
        run: cargo fmt -- --check

  test:
    needs: build
    runs-on: ubuntu-latest
    
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90

      - name: sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Run tests
        run: cargo test --verbose --workspace --all-targets --no-fail-fast

      - name: Run doc tests
        run: cargo test --verbose --workspace --doc --features doctest --no-fail-fast

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-features --workspace -- -Dwarnings

  fix-flaws:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mdn/rari
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: rari
          persist-credentials: false

      - name: Checkout mdn/content
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: mdn/content
          path: content
          persist-credentials: false

      - name: Checkout mdn/translated-content
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: mdn/translated-content
          path: translated-content
          persist-credentials: false

      - name: Download rari binary
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: rari-binary
          path: rari/target/release

      - name: Make rari executable
        run: chmod +x rari/target/release/rari

      - name: Run fix-flaws
        working-directory: rari
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: target/release/rari content fix-flaws

      - name: Show content changes
        working-directory: content
        run: git diff --color=always --word-diff --word-diff-regex='[[:alnum:]_]+'

      - name: Show translated-content changes
        working-directory: translated-content
        run: git diff --color=always --word-diff --word-diff-regex='[[:alnum:]_]+'
